# These are supported funding model platforms

# github: [yourusername]
# patreon: yourusername
# open_collective: project-name
# ko_fi: yourusername
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# lfx_crowdfunding: project-name
# polar: username
# buy_me_a_coffee: username
# thanks_dev: username
# custom: ['https://yourwebsite.com/donate']
